FROM centos:7
RUN yum -y install epel-release
RUN yum -y install postgresql-libs
RUN yum -y install python36
RUN yum -y install python36-devel
RUN yum -y install which
RUN yum -y install nginx
RUN yum -y install gcc
COPY ./docker/scripts/* /usr/bin/
WORKDIR /usr/src/app
ENTRYPOINT ["entrypoint.sh"]
