version: '2.1'
services:

  app:
    image: forecast_api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    environment:
      - ENVIRONMENT=development

  tests:
    extends: app
    image: forecast_api-tests
    command: run-tests.sh
